server {
    listen       80;
    server_name  localhost;

    # Necesario en Windows/WSL2: sin esto nginx tira "Invalid argument"
    sendfile off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }
}
